services:
  - type: web
    name: apoorva-hair-salon-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: salon-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
